version: "3"
services:
  client:
    build:
      context: .frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend

  web:
    build:
      context: ./Task/backend
      dockerfile: Task/frontend/Dockerfile
    ports:
      - ${PORT}:5000
    working_dir: /src
    command: python ./app.py
    networks:
      - frontend
      - backend

  mariadb:
    image: mysql:5.7
    container_name: mariadb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${PWD}/mysqldb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
   mariadbdata:
      driver: local
   appdata:
      driver: local