version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:5000
    env_file:
      - .env
    working_dir: /src
    command: python ./app.py

  mariadb:
    image: mysql:5.7
    container_name: mariadb_container
#    command: --default-authentication-plugin=mysql_native_password
#    command: [--ignore-db-dir=lost+found]
    volumes:
      - ${PWD}/mysqldb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

